import { Ship, Route, Booking, Review, Cabin } from '@/types';

export const CABIN_TYPES = {
  'single-riverside': {
    name: 'Single Riverside Cabin',
    icon: '🪟',
    description: 'Single cabin with riverside view',
    basePrice: 2500,
  },
  'single-inside': {
    name: 'Single Inside Cabin',
    icon: '🚪',
    description: 'Single cabin inside the ship',
    basePrice: 1800,
  },
  double: {
    name: 'Double Cabin',
    icon: '🛏️',
    description: 'Comfortable double cabin for couples',
    basePrice: 4000,
  },
  family: {
    name: 'Family Cabin',
    icon: '👨‍👩‍👧‍👦',
    description: 'Spacious cabin for families',
    basePrice: 6000,
  },
  vip: {
    name: 'VIP Cabin',
    icon: '👑',
    description: 'Luxury VIP cabin with premium amenities',
    basePrice: 10000,
  },
};

export const mockShips: Ship[] = [
  {
    id: 'ship-1',
    name: 'Riverside Princess',
    operator: 'Bengal River Cruises',
    ownerId: 'owner-1',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=500',
    description: 'Luxury cruise ship with world-class amenities',
    rating: 4.8,
    reviews: 342,
    cabins: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ship-2',
    name: 'Bengal Express',
    operator: 'Delta Shipping',
    ownerId: 'owner-2',
    image: 'https://images.unsplash.com/photo-1522068847285-baa5da2621b4?w=500',
    description: 'Modern passenger ferry with comfortable cabins',
    rating: 4.5,
    reviews: 218,
    cabins: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ship-3',
    name: 'Ganges Luxury',
    operator: 'Premium River Tours',
    ownerId: 'owner-1',
    image: 'https://images.unsplash.com/photo-1528127269029-c440edc5a5cd?w=500',
    description: 'Five-star riverside accommodation and dining',
    rating: 4.9,
    reviews: 487,
    cabins: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ship-4',
    name: 'Coastal Voyager',
    operator: 'Maritime Services Ltd',
    ownerId: 'owner-3',
    image: 'https://images.unsplash.com/photo-1535585566273-7e3e36cba5c4?w=500',
    description: 'Budget-friendly passenger ferry for daily routes',
    rating: 4.2,
    reviews: 156,
    cabins: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ship-5',
    name: 'River Ambassador',
    operator: 'Bengal River Cruises',
    ownerId: 'owner-1',
    image: 'https://images.unsplash.com/photo-1559395007-c4ff2b952b11?w=500',
    description: 'Classic heritage ship with traditional decor',
    rating: 4.6,
    reviews: 295,
    cabins: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockRoutes: Route[] = [
  {
    id: 'route-1',
    shipId: 'ship-1',
    departurePort: 'Dhaka River Terminal',
    destinationPort: 'Chittagong Port',
    departureTime: '08:00',
    arrivalTime: '16:30',
    duration: 8.5,
    date: new Date().toISOString().split('T')[0],
    seatsAvailable: 45,
    totalSeats: 200,
    basePrice: 3500,
    status: 'active',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'route-2',
    shipId: 'ship-2',
    departurePort: 'Dhaka River Terminal',
    destinationPort: 'Sylhet Jetty',
    departureTime: '10:00',
    arrivalTime: '18:00',
    duration: 8,
    date: new Date().toISOString().split('T')[0],
    seatsAvailable: 120,
    totalSeats: 180,
    basePrice: 2800,
    status: 'active',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'route-3',
    shipId: 'ship-3',
    departurePort: 'Dhaka River Terminal',
    destinationPort: 'Khulna Port',
    departureTime: '06:00',
    arrivalTime: '15:45',
    duration: 9.75,
    date: new Date().toISOString().split('T')[0],
    seatsAvailable: 30,
    totalSeats: 150,
    basePrice: 5000,
    status: 'active',
    createdAt: new Date().toISOString(),
  },
];

export const mockCabins: Cabin[] = [
  {
    id: 'cabin-1',
    type: 'single-riverside',
    number: 'A101',
    capacity: 1,
    basePrice: 2500,
    amenities: ['River View', 'Ensuite Bathroom', 'AC'],
    shipId: 'ship-1',
  },
  {
    id: 'cabin-2',
    type: 'double',
    number: 'A102',
    capacity: 2,
    basePrice: 4000,
    amenities: ['King Bed', 'River View', 'Ensuite Bathroom', 'AC', 'Mini Bar'],
    shipId: 'ship-1',
  },
  {
    id: 'cabin-3',
    type: 'family',
    number: 'B201',
    capacity: 4,
    basePrice: 6000,
    amenities: ['2 Bedrooms', 'Living Area', 'Kitchenette', 'Balcony', 'AC'],
    shipId: 'ship-1',
  },
  {
    id: 'cabin-4',
    type: 'vip',
    number: 'VIP01',
    capacity: 2,
    basePrice: 10000,
    amenities: [
      'Luxury Suite',
      'Panoramic View',
      'Jacuzzi',
      'Premium Toiletries',
      'Champagne',
      'Private Butler',
    ],
    shipId: 'ship-1',
  },
];

export const mockBookings: Booking[] = [
  {
    id: 'booking-1',
    userId: 'user-1',
    routeId: 'route-1',
    items: [
      {
        cabinId: 'cabin-1',
        cabinType: 'single-riverside',
        cabinNumber: 'A101',
        quantity: 1,
        pricePerUnit: 2500,
      },
    ],
    totalPrice: 2500,
    status: 'confirmed',
    passengers: [
      {
        id: 'passenger-1',
        firstName: 'John',
        lastName: 'Doe',
        email: 'john@example.com',
        phone: '+1234567890',
        age: 35,
        documentType: 'Passport',
        documentNumber: 'ABC123456',
        gender: 'male',
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockReviews: Review[] = [
  {
    id: 'review-1',
    userId: 'user-1',
    shipId: 'ship-1',
    rating: 5,
    comment: 'Excellent service and comfortable cabins!',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'review-2',
    userId: 'user-2',
    shipId: 'ship-1',
    rating: 4,
    comment: 'Good experience, though food could be better.',
    createdAt: new Date().toISOString(),
  },
];
